### ISSUE TITLE
Buffer size reading incomplete fragments

### ISSUE THREAD

**Issue by asniaire** [Azolo/websockex#78]
Hi, I'm getting an issue when reading websocket fragments. According to my tests,`websockex` reads always from the socket up to 4380 bytes to fill its buffer (I don't know where this buffer size comes from). And I'm receiving websocket fragments (according to wireshark) with 4152 bytes.

So, the library reads the first fragment complete (4152 bytes) and from the second one reads only 228 bytes (4380 - 4152 bytes). It parses perfectly the first fragment and when it parses the second one, reads the header, gets the payload length and when it tries:

```elixir
  def parse_frame(<<1::1, 0::3, 0::4, 0::1, 126::7, len::16, remaining::bitstring>>) do
    <<payload::bytes-size(len), rest::bitstring>> = remaining # <-------- failing line
    {:ok, {:finish, payload}, rest}
  end
``` 
I got the error:
```
** (MatchError) no match of right hand side value: "\"avg_hire_time\":0}},{\"cell_id\":\"NY2371707\",\"score\":0,\"real_time\":{\"score\":0,\"recent_journeys\":1,\"recent_unique_users_requesting\":0,\"queued_journeys_now\":0,\"avg_hire_time\":0}},{\"cell_id\":\"NY2371243\",\"score\":0,\"real_time\":{\"score\":0,\"recent_journeys\":1,\"recent_unique_users_requesting\":1,\"que"
        (websockex) lib/websockex/frame.ex:144: WebSockex.Frame.parse_frame/1
        (websockex) lib/websockex.ex:462: WebSockex.websocket_loop/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

because `bytes-size(len)` is the length of the whole fragment (according to websocket protocol) but the buffer contains only partially the second fragment. So, it fails doing

`<<payload::bytes-size(len), rest::bitstring>> = remaining`

The library manages well the fragments except when the buffer contains multiple fragments and some of them are not complete. So, the library assumes that a fragment is always longer than 4138 bytes, but my fragments contains 4152 bytes.

Is there a way of setting up the buffer size? Otherwise, have you ever faced this issue?

Thanks!

**Comment by asniaire** [comment]
Hi again! I've tried a quick fix and I think it works. 

I'm using version `0.3.1` but it's the same in last version `0.4.2`. 

In the explained issue, the second fragment comes with `opcode = 0`, indicating `continuation` (as explained in the [RFC 6455](https://tools.ietf.org/html/rfc6455#section-5.2)).

In `frame.ex`, the generated code to parse incomplete payloads doesn't consider this case (only `text` and `binary`)
```elixir
for {_key, opcode} <- Map.take(@opcodes, [:text, :binary]) do
    def parse_frame(
          <<_::1, 0::3, unquote(opcode)::4, 0::1, 126::7, len::16, remaining::bitstring>>
        )
        when byte_size(remaining) < len do
      :incomplete
    end

    def parse_frame(
          <<_::1, 0::3, unquote(opcode)::4, 0::1, 127::7, len::64, remaining::bitstring>>
        )
        when byte_size(remaining) < len do
      :incomplete
    end
  end
```
After adding `@opcodes %{continuation: 0, text: 1, binary: 2, close: 8, ping: 9, pong: 10}`
and
```elixir
for {_key, opcode} <- Map.take(@opcodes, [:continuation, :text, :binary]) do
...
end
```
it works and never cashes.

I'll create a PR with this change to be reviewed :)
